package com.ormlearn.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GROUP 1 — Hands-on 6, 7, 8, 9 | GROUP 2 — Hands-on 1
 *
 * JPA Entity representing a Country.
 *
 * TABLE: country
 * +----------+-----------+
 * | co_code  | co_name   |
 * +----------+-----------+
 * | IN       | India     |
 * | US       | United States |
 * +----------+-----------+
 *
 * WHY String PK (no @GeneratedValue)?
 * Country codes are natural business keys (ISO 3166-1 alpha-2).
 * They do not need to be auto-generated by the database.
 *
 * JPA ANNOTATIONS USED:
 * @Entity     — marks this class as a JPA-managed entity
 * @Table      — maps to the "country" table in DB
 * @Id         — designates the primary key field
 * @Column     — maps field to specific DB column name
 *
 * INTERVIEW Q: What happens if @Column is omitted?
 * A: Hibernate uses the field name as the column name (case-insensitive).
 */
@Entity
@Table(name = "country")
public class Country {

    @Id
    @Column(name = "co_code", length = 3)
    private String code;

    @Column(name = "co_name", nullable = false, length = 100)
    private String name;

    // ---- Constructors ----
    public Country() {
    }

    public Country(String code, String name) {
        this.code = code;
        this.name = name;
    }

    // ---- Getters & Setters ----
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // ---- toString ----
    @Override
    public String toString() {
        return "Country [code=" + code + ", name=" + name + "]";
    }
}
